import { useEffect,useMemo,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import api from '../api'

const flow=['REQUESTED','ACCEPTED','CHECKED_OUT','IN_USE','RETURNED','CHECKED_APPROVED','CLOSED']
const nextFor={REQUESTED:['ACCEPTED','REJECTED'],ACCEPTED:['CHECKED_OUT'],CHECKED_OUT:['IN_USE','RETURNED'],IN_USE:['RETURNED','DAMAGE_REPORTED'],RETURNED:['CHECKED_APPROVED','DAMAGE_REPORTED'],DAMAGE_REPORTED:['CHECKED_APPROVED'],CHECKED_APPROVED:['CLOSED']}
export default function RentalDetails(){
 const {rentalId}=useParams(),nav=useNavigate()
 const [r,setR]=useState(null),[userId,setUserId]=useState(localStorage.getItem('rentallUserId')||''),[users,setUsers]=useState([])
 const [tab,setTab]=useState('overview'),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 const [loc,setLoc]=useState({address:'',latitude:'',longitude:'',radiusKm:'1.2'}),[spot,setSpot]=useState({name:'',address:'',latitude:'',longitude:'',placeId:''})
 const [status,setStatus]=useState({newStatus:'',note:''}),[otp,setOtp]=useState({purpose:'CHECKOUT',code:'',match:true}),[otpInfo,setOtpInfo]=useState(null)
 const [damage,setDamage]=useState({description:'',estimatedCost:'',photos:''}),[incidents,setIncidents]=useState([])
 const load=async()=>{try{const x=await api.get(`/api/rentals/${rentalId}`);setR(x.data.rental);if(x.data.rental.pickupLocation)setLoc({...x.data.rental.pickupLocation,radiusKm:x.data.rental.pickupRadiusKm});if(x.data.rental.handoverSpot)setSpot(x.data.rental.handoverSpot);const d=await api.get(`/api/rentals/${rentalId}/damage`);setIncidents(d.data.damageIncidents||[])}catch(e){setErr(e.response?.data?.message||'Failed to load rental.')}}
 useEffect(()=>{load();api.get('/api/catalog/users').then(x=>{setUsers(x.data.users);if(!userId&&x.data.users[0]){setUserId(x.data.users[0]._id);localStorage.setItem('rentallUserId',x.data.users[0]._id)}})},[rentalId])
 const me=users.find(u=>u._id===userId)
 const next=useMemo(()=>nextFor[r?.status]||[],[r])
 const action=async fn=>{setErr('');setMsg('');try{await fn();setMsg('Saved successfully.');await load()}catch(e){setErr(e.response?.data?.message||'Operation failed.')}}
 if(!r)return <div className="container page"><p>{err||'Loading...'}</p></div>
 const updateStatus=()=>action(()=>api.put(`/api/rentals/${rentalId}/status`,{newStatus:status.newStatus,actorId:userId,note:status.note}))
 const geocode=async()=>action(async()=>{const x=await api.get('/api/maps/geocode',{params:{address:loc.address}});setLoc(v=>({...v,address:x.data.formattedAddress,latitude:x.data.latitude,longitude:x.data.longitude}))})
 const saveLoc=()=>action(()=>api.put(`/api/rentals/${rentalId}/pickup-location`,{...loc,actorId:userId}))
 const propose=()=>action(()=>api.post(`/api/rentals/${rentalId}/handover-spot`,{...spot,proposedBy:userId,source:'GOOGLE_MAPS'}))
 const confirm=()=>action(()=>api.put(`/api/rentals/${rentalId}/handover-spot/confirm`,{userId}))
 const genOtp=()=>action(async()=>{const x=await api.post(`/api/rentals/${rentalId}/handover-otp`,{purpose:otp.purpose,requestedBy:userId});setOtpInfo(x.data);setOtp(v=>({...v,code:x.data.otp||''}))})
 const verify=()=>action(()=>api.post(`/api/rentals/${rentalId}/handover-verify`,{otp:otp.code,itemMatchesDescription:otp.match,userId}))
 const report=()=>action(()=>api.post(`/api/rentals/${rentalId}/damage`,{reportedBy:userId,description:damage.description,estimatedCost:Number(damage.estimatedCost||0),photos:damage.photos?damage.photos.split(',').map(x=>x.trim()).filter(Boolean):[]}))
 const resolve=(id,resolution,status='RESOLVED')=>action(()=>api.put(`/api/rentals/damage/${id}`,{status,resolution,resolvedBy:userId}))
 return <div className="container page">
  <button className="btn btn-secondary" onClick={()=>nav('/dashboard')}>← Dashboard</button>
  <div className="page-head"><div><h1>{r.itemId?.title}</h1><span className={`status ${r.status}`}>{r.status.replaceAll('_',' ')}</span></div>
   <label className="user-switch">Acting as<select value={userId} onChange={e=>{setUserId(e.target.value);localStorage.setItem('rentallUserId',e.target.value)}}>{users.map(u=><option key={u._id} value={u._id}>{u.name} ({u.role})</option>)}</select></label>
  </div>
  {err&&<div className="alert alert-error">{err}</div>}{msg&&<div className="alert alert-success">{msg}</div>}
  <div className="card summary"><div><b>Renter</b><span>{r.renterId?.name}</span></div><div><b>Lender</b><span>{r.lenderId?.name}</span></div><div><b>Period</b><span>{new Date(r.startDate).toLocaleDateString()} → {new Date(r.endDate).toLocaleDateString()}</span></div><div><b>Amount</b><span>৳{r.rentalAmount}</span></div><div><b>Deposit</b><span>{r.depositStatus}</span></div><div><b>Payment</b><span>{r.paymentStatus}</span></div></div>
  <div className="tabs">{['overview','status','location','handover','damage'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
  {tab==='overview'&&<div className="card"><h2>Lifecycle History</h2><div className="timeline">{r.statusHistory?.map((h,i)=><div className="timeline-item" key={i}><b>{h.status.replaceAll('_',' ')}</b><span>{new Date(h.at).toLocaleString()}</span><p>{h.note||'—'} {h.actorId?.name&&`• ${h.actorId.name}`}</p></div>)}</div></div>}
  {tab==='status'&&<div className="card"><h2>Feature 12 • Status Workflow</h2><div className="flow">{flow.map((s,i)=><span key={s} className={r.status===s?'current':''}>{s.replaceAll('_',' ')}{i<flow.length-1?' → ':''}</span>)}</div><div className="form-grid"><label>Next status<select value={status.newStatus} onChange={e=>setStatus({...status,newStatus:e.target.value})}><option value="">Choose...</option>{next.map(s=><option key={s}>{s}</option>)}</select></label><label>Note<textarea value={status.note} onChange={e=>setStatus({...status,note:e.target.value})}/></label></div><button className="btn btn-primary" disabled={!status.newStatus||!me} onClick={updateStatus}>Update Status</button><p className="muted">CHECKED_OUT and RETURNED are intentionally OTP-only.</p></div>}
  {tab==='location'&&<div className="card"><h2>Feature 13 • Geographic Exchange Mapper</h2><div className="form-grid"><label>Pickup address<input value={loc.address||''} onChange={e=>setLoc({...loc,address:e.target.value})}/></label><button className="btn btn-secondary" onClick={geocode}>Geocode with Google Maps</button><label>Latitude<input type="number" step="any" value={loc.latitude??''} onChange={e=>setLoc({...loc,latitude:e.target.value})}/></label><label>Longitude<input type="number" step="any" value={loc.longitude??''} onChange={e=>setLoc({...loc,longitude:e.target.value})}/></label><label>Radius (km)<input type="number" step="0.1" min="0.1" max="25" value={loc.radiusKm||''} onChange={e=>setLoc({...loc,radiusKm:e.target.value})}/></label></div><button className="btn btn-primary" onClick={saveLoc}>Save Pickup Location</button>{r.pickupLocation&&<p><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${r.pickupLocation.latitude},${r.pickupLocation.longitude}`}>Open pickup on Google Maps ↗</a></p>}<hr/><h3>Public Handover Spot</h3><div className="form-grid"><label>Name<input value={spot.name||''} onChange={e=>setSpot({...spot,name:e.target.value})}/></label><label>Address<input value={spot.address||''} onChange={e=>setSpot({...spot,address:e.target.value})}/></label><label>Latitude<input type="number" step="any" value={spot.latitude??''} onChange={e=>setSpot({...spot,latitude:e.target.value})}/></label><label>Longitude<input type="number" step="any" value={spot.longitude??''} onChange={e=>setSpot({...spot,longitude:e.target.value})}/></label></div><button className="btn btn-primary" onClick={propose}>Propose Spot</button>{r.handoverSpot?.name&&<div className="info-box"><b>{r.handoverSpot.name}</b><br/>{r.handoverSpot.address}<br/><button className="btn btn-secondary" onClick={confirm}>Confirm as {me?.role}</button> <a target="_blank" rel="noreferrer" href={r.handoverSpot.mapsUrl}>Open Map ↗</a><p>Renter: {r.handoverSpot.confirmedByRenter?'✓':'—'} &nbsp; Lender: {r.handoverSpot.confirmedByLender?'✓':'—'}</p></div>}</div>}
  {tab==='handover'&&<div className="card"><h2>Feature 14 • Handover Verification</h2><p>Both parties must confirm the handover spot before OTP generation.</p><label>Purpose<select value={otp.purpose} onChange={e=>setOtp({...otp,purpose:e.target.value})}><option>CHECKOUT</option><option>RETURN</option></select></label><br/><button className="btn btn-primary" onClick={genOtp}>Generate OTP</button>{otpInfo&&<div className="info-box">Expires: {new Date(otpInfo.expiresAt).toLocaleString()}{otpInfo.otp&&<><br/><b>Development OTP: {otpInfo.otp}</b></>}</div>}<hr/><label>OTP<input inputMode="numeric" maxLength="6" value={otp.code} onChange={e=>setOtp({...otp,code:e.target.value})}/></label><label><input type="checkbox" checked={otp.match} onChange={e=>setOtp({...otp,match:e.target.checked})}/> Item/condition matches the description</label><br/><button className="btn btn-primary" onClick={verify}>Verify Handover</button><p className="muted">OTP expires after 15 minutes and allows only 3 failed attempts. Twilio SMS is used when configured.</p></div>}
  {tab==='damage'&&<div className="card"><h2>Feature 15 • Damage Incident & Escrow</h2><div className="form-grid"><label>Description<textarea value={damage.description} onChange={e=>setDamage({...damage,description:e.target.value})}/></label><label>Estimated cost (৳)<input type="number" min="0" value={damage.estimatedCost} onChange={e=>setDamage({...damage,estimatedCost:e.target.value})}/></label><label>Photo URLs (comma separated)<input value={damage.photos} onChange={e=>setDamage({...damage,photos:e.target.value})}/></label></div><button className="btn btn-primary" onClick={report}>Report Damage & Freeze Escrow</button><hr/><h3>Incidents</h3>{incidents.map(i=><div className="incident" key={i._id}><b>{i.status}</b> • ৳{i.estimatedCost}<p>{i.description}</p><small>Reported by: {i.reportedBy?.name}</small>{['OPEN','UNDER_REVIEW'].includes(i.status)&&String(r.lenderId?._id||r.lenderId)===String(userId)&&<div><button className="btn btn-secondary" onClick={()=>resolve(i._id,'NO_ACTION')}>Reject / Release</button><button className="btn btn-primary" onClick={()=>resolve(i._id,'DEDUCT_FROM_DEPOSIT')}>Resolve / Deduct Deposit</button></div>}</div>)}</div>}
 </div>
}
